### ISSUE TITLE
Questions about dependencies

### ISSUE THREAD

**Issue by jbergknoff-rival** [optimizely/python-sdk#232]
Hi, we're considering pulling in this SDK in several Python projects. Because we build those projects in pretty bare containers, the compiled dependencies here (`mmh3`, and `cryptography` from `requests[security]`) mean that we need to install some additional OS packages at build time. That's not a showstopper, but some questions came up:

* Is `requests[security]` needed? From https://github.com/psf/requests/pull/4825/files, it seems like it's probably not needed anymore, since fixes have been introduced in the standard library in Python 2.7.9 and 3.4.3.

* There is already fallback code in case `mmh3` isn't installed: https://github.com/optimizely/python-sdk/blob/d3ffe336de677e7dafff03253aa6c9adc49cf326/optimizely/bucketer.py#L16-L19, but the `mmh3` requirement doesn't seem to be optional. Could it be made optional?

* Do you have any details on the performance penalty of using the pure-Python Murmur3 implementation, as compared to the compiled version? I suspect that, in our use case (AWS Lambda, process per request), it may not be an issue.

**Comment by scottanderson42** [comment]
In a similar vein, the Optimizely `jsonschema` dependency (==2.6.0) is conflicting with that of the `boto` packages (~=3.0).

**Comment by jonfreeland** [comment]
> In a similar vein, the Optimizely `jsonschema` dependency (==2.6.0) is conflicting with that of the `boto` packages (~=3.0).

We are also encountering issues with the `jsonschema` dependency conflicting with [Poetry](https://python-poetry.org/) 0.12.17. Can we get an update on this issue?

**Comment by aliabbasrizvi** [comment]
We are bumping `jsonschema` and will release a new SDK which should hopefully address the issue.

**Comment by aliabbasrizvi** [comment]
> mmh3 requirement doesn't seem to be optional

`mmh3` is the standard way to do bucketing across all Optimizely SDKs and so that ensures that experience delivery is consistent throughout the stack irrespective of which SDK you use. 

Unfortunately, I do not have numbers comparing the performance of the 2 mmh3 implementations. There is a reference to performance from the original authors here: https://github.com/wc-duck/pymmh3#performance

I'll get back on the question about `requests[security]`.

**Comment by aliabbasrizvi** [comment]
@jonfreeland  @scottanderson42 release [3.4.1](https://pypi.org/project/optimizely-sdk/3.4.1) is available with updated `jsonschema` package. Hopefully that addresses the issue you ran into.

**Comment by daviddomingoslalom** [comment]
Hey @aliabbasrizvi seems like the mmh3 lib is giving us some trouble in our docker image because we don't have the c++ compiler installed. I googled the issue and it looks like other people are running into the same thing: https://github.com/hajimes/mmh3/issues/20

The author seems to have abandoned the project so I don't see any solution in the near future. What do you suggest we do? Should we just use the API directly via http?

**Comment by GordonSo** [comment]
Notice that mmh has released 3.0.0 - do you need contributors to help bump that up?

**Comment by The-inside-man** [comment]
This issue is now closed and will be part of the next release of the python-sdk.
https://github.com/optimizely/python-sdk/pull/362
