### ISSUE TITLE
Python SDK docs not available

### ISSUE THREAD

**Issue by dave-kielpinski-circleci** [optimizely/python-sdk#238]
there is no link to the Python SDK docs, and the Full-Stack Docs don't currently have a working link to the Python SDK

**Comment by asaschachar** [comment]
Hi @dave-kielpinski-circleci,

Thanks for pointing out improvements we can make to our links.

Just to clarify, would you like to see a link directly to (https://docs.developers.optimizely.com/full-stack/docs/python) in the README.md of this repo?

And then would you also like to have a link to the Python SDK on its package manager (https://pypi.org/project/optimizely-sdk/) in the Python documentation linked above?

Thanks in advance!

**Comment by dave-kielpinski-circleci** [comment]
sure, that would be great, but i am also pointing out that the doc links are broken on your main website. i left a comment there as well

**Comment by The-inside-man** [comment]
Good Day,

The following link to the full-stack documentation is located [here](https://github.com/optimizely/python-sdk/blob/master/README.md#:~:text=For%20Further%20details%20see%20the%20Optimizely%20Full%20Stack%20documentation%20to%20learn%20how%20to%20set%20up%20your%20first%20Python%20project%20and%20use%20the%20SDK)

When looking at the developer documentation for the Python SDK, the main page has a direct link this repository, located [here](https://docs.developers.optimizely.com/full-stack/docs/python-sdk#:~:text=Source%20files-,Python%20SDK%20repo,-changelog)

If there are any broken links that persist, please let us know and we will make sure the right people are made aware, so that they may be fixed. 

Thank you for bringing this to our attention!
