### ISSUE TITLE
Need to dispatch to logx.* endpoints

### ISSUE THREAD

**Issue by osule** [optimizely/python-sdk#79]
Events dispatched to logx.* sub-domain can take a response time of 0.407 sec.

Are [these endpoints](https://github.com/optimizely/python-sdk/blob/1.2.0/optimizely/event_builder.py#L102-L103) service critical? 
Is there any reason not to dispatch events to them if the JS client is already logging I think?

@bradtaylorsf @dsiroker @koomen @travisbeck @loganlinn

**Comment by aliabbasrizvi** [comment]
@osule thank you for your question.

It is required to dispatch events to them, because these events are what come to our backend and then power the results.

Regarding the response time, the event dispatcher that we provide is just a sample implementation and you can certainly override it when initializing [optimizely.Optimizely](https://github.com/optimizely/python-sdk/blob/master/optimizely/optimizely.py#L35) and provide your own implementation.

Hope this helps.

**Comment by osule** [comment]
Yes it helps to clarify my concern. Thank you.
